name: Test OnePassword installation script

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run install-onepassword script
        run: bash scripts/install-onepassword.sh
